version: '3.9'

services:
  frontend:
    container_name: frontend
    image: frontend
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
    ports:
      - 3000:3000
    env_file:
      - ./frontend/.env.local
    depends_on:
      - backend
    networks:
      - mynetwork
  backend:
    container_name: backend
    image: backend
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    ports:
      - 5000:5000
    env_file:
      - ./backend/config/config.env
    networks:
      - mynetwork
  mongo:
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME : root
      MONGO_INITDB_ROOT_PASSWORD : root
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
    networks:
      - mynetwork

volumes:
  mongodata:
    driver: local

networks:
  mynetwork:
    name: mynetwork
    driver: bridge


  